version: "3.9"
services:
  quartz-demo:
    image: "docker.io/syalioune/quartz-zookeeper:0.0.1-SNAPSHOT"
    ports:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JDBC_URL: "jdbc:postgresql://postgres:5432/postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "mysecretpassword"
      ZK_CONNECT_STRING: "zookeeper:2181"
    depends_on:
      - "postgres"
      - "zookeeper"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
  zookeeper:
    image: "zookeeper"