spring:
  h2:
    console:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 10
      org.quartz.scheduler.instanceName: ${spring.application.name}
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.isClustered: true
      org.quartz.plugin.shutdownHook.class: org.quartz.plugins.management.ShutdownHookPlugin
      org.quartz.plugin.shutdownHook.cleanShutdown: true
      org.quartz.jobStore.lockHandler.class: fr.syalioune.scheduling.quartz.semaphore.ZookeeperSemaphore
      org.quartz.jobStore.lockHandler.zookeeperConnectString: ${ZK_CONNECT_STRING}
      org.quartz.jobStore.lockHandler.zookeeperLockPath: /quartz/leader
      org.quartz.jobStore.lockHandler.zookeeperRetryMs: 100
      org.quartz.jobStore.lockHandler.leadershipPeriodMs: 120000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect